name: PR Checks

on: [pull_request]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 18
      - run: pnpm install:all
      - run: pnpm audit:all
      - run: pnpm circular:check
        if: success() || failure()
      - run: pnpm compile:all
        if: success() || failure()
      - run: pnpm css:check
        if: success() || failure()
      - run: pnpm format:check
        if: success() || failure()
      - run: pnpm lint
        if: success() || failure()
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v2
        with:
          languages: javascript-typescript
      - uses: github/codeql-action/analyze@v2
